### ISSUE TITLE
✅ [FEATURE] 작업 환경 세팅

### ISSUE THREAD

**Issue by dananote** [React-Commerce-Study/taehee-Rho#1]
## Description
앞으로 작업하기 위한 작업환경 세팅

## To-do
- [X] react 생성 및 github 연결
- [X] img asset 추가
- [X] font, color components추가
- [X] 스타일 초기화
