### ISSUE TITLE
✅[FEATURE] Carousel 기능구현

### ISSUE THREAD

**Issue by dananote** [React-Commerce-Study/taehee-Rho#4]
## Description
 event bannel 에 Carousel 기능 활용 

## To-do
- [x] event banner 더미 데이터 생성
- [x] 이미지가 event banner 에 노출되고 각이미지 마다 클릭 이벤트시 해당 page 로 이동
- [x] next, prev btn 클릭시 이미지가 사용자가 원하는 이미지로 넘어감
- [x] 인디케이터로 생성
- [x] 일정 시간이 지나면 자동으로 다음 이미지로 넘어감

## ETC
<진행 과정 정리>
https://masankong.tistory.com/48
<라이브러리> (현재 사용하지 X)
https://swiperjs.com/demos﻿
https://www.embla-carousel.com/﻿
